version: "3.9"

services:
  server:
    build:
      context: docker/development
      args:
        UID: $UID
        GID: $GID
    container_name: server
    hostname: server
    command: ["npm", "run", "dev"]
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: noterr
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
